apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: invoiceflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Subhitcha04/invoiceflow-config.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: invoiceflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true