apiVersion: v1
kind: Service
metadata:
  name: invoiceflow-active
  namespace: invoiceflow
spec:
  selector:
    app: invoiceflow
    slot: blue        # ← change this to "green" when switching
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer