apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoiceflow-green
  namespace: invoiceflow
  labels:
    app: invoiceflow
    slot: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: invoiceflow
      slot: green
  template:
    metadata:
      labels:
        app: invoiceflow
        slot: green
    spec:
      serviceAccountName: default
      containers:
        - name: api
          image: asia-south1-docker.pkg.dev/cat-2-491109/invoiceflow/api:latest
          ports:
            - containerPort: 8000
          env:
            - name: GCP_PROJECT_ID
              value: "cat-2-491109"
            - name: GOOGLE_CLOUD_PROJECT
              value: "cat-2-491109"
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10